export const CLIENTS = [
  {
    id: 'movistar',
    name: 'Movistar',
    logo: '/logos/movistar-logo.png',
    category: 'Telecom',
    tagline: 'Soporte para tus servicios móviles y de internet',
    primaryColor: '#8B5CF6',
    agentsAvailable: 12,
    config: {
      botName: 'Asistente Movistar',
      botSubtitle: 'Centro de atención',
      primaryColor: '#8B5CF6',
      clientLogo: '/logos/movistar-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Movistar. ¿En qué puedo ayudarte hoy?',
      quickReplies: [
        { label: 'Ver mi factura', value: 'bill' },
        { label: 'Reportar un problema técnico', value: 'issue' },
        { label: 'Cambiar mi plan', value: 'plan' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'mv-1', title: '¿Cómo consultar mi saldo y consumo?', mins: 2 },
        { id: 'mv-2', title: '¿Cómo ver y pagar mi factura online?', mins: 3 },
        { id: 'mv-3', title: '¿Qué hacer si no tengo señal?', mins: 3 },
        { id: 'mv-4', title: 'Portabilidad numérica a Movistar', mins: 4 },
        { id: 'mv-5', title: '¿Cómo cambiar mi plan de telefonía?', mins: 3 },
        { id: 'mv-6', title: 'Activar roaming internacional', mins: 4 },
        { id: 'mv-7', title: '¿Cómo configurar el correo de voz?', mins: 2 },
      ],
    },
  },
  {
    id: 'claro',
    name: 'Claro',
    logo: '/logos/claro-logo.png',
    category: 'Telecom',
    tagline: 'Atención al cliente para todos tus servicios Claro',
    primaryColor: '#DC2626',
    agentsAvailable: 8,
    config: {
      botName: 'Asistente Claro',
      botSubtitle: 'Soporte 24/7',
      primaryColor: '#DC2626',
      clientLogo: '/logos/claro-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Claro. ¿Cómo puedo ayudarte?',
      quickReplies: [
        { label: 'Consultar saldo', value: 'balance' },
        { label: 'Problemas con mi línea', value: 'line_issue' },
        { label: 'Portabilidad', value: 'portability' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'cl-1', title: '¿Cómo revisar mi saldo disponible?', mins: 2 },
        { id: 'cl-2', title: 'Portabilidad numérica: cómo hacerla', mins: 4 },
        { id: 'cl-3', title: 'Problemas con internet móvil: soluciones', mins: 3 },
        { id: 'cl-4', title: '¿Cómo activar roaming internacional?', mins: 3 },
        { id: 'cl-5', title: '¿Dónde y cómo pagar mi factura Claro?', mins: 2 },
        { id: 'cl-6', title: '¿Cómo cambiar mi plan prepago o pospago?', mins: 3 },
        { id: 'cl-7', title: 'Bloqueo y desbloqueo de línea', mins: 2 },
      ],
    },
  },
  {
    id: 'sicredi',
    name: 'Sicredi',
    logo: '/logos/sicredi-logo-1.png',
    category: 'Banca',
    tagline: 'Tu cooperativa de crédito siempre disponible',
    primaryColor: '#16A34A',
    agentsAvailable: 5,
    config: {
      botName: 'Asistente Sicredi',
      botSubtitle: 'Cooperativa de crédito',
      primaryColor: '#16A34A',
      clientLogo: '/logos/sicredi-logo-1.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Sicredi. ¿En qué puedo ayudarte hoy?',
      quickReplies: [
        { label: 'Consultar mi cuenta', value: 'account' },
        { label: 'Solicitar un crédito', value: 'credit' },
        { label: 'Inversiones', value: 'investments' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'sc-1', title: '¿Cómo asociarme a Sicredi?', mins: 4 },
        { id: 'sc-2', title: '¿Cómo acceder al internet banking?', mins: 2 },
        { id: 'sc-3', title: '¿Cómo solicitar un crédito cooperativo?', mins: 5 },
        { id: 'sc-4', title: 'Tasas y rendimiento de inversiones', mins: 4 },
        { id: 'sc-5', title: '¿Qué es una cooperativa de crédito?', mins: 3 },
        { id: 'sc-6', title: 'Transferencias y pagos desde mi cuenta', mins: 2 },
        { id: 'sc-7', title: '¿Cómo solicitar mi tarjeta de débito?', mins: 3 },
      ],
    },
  },
  {
    id: 'felix',
    name: 'Félix',
    logo: '/logos/sicredi-logo.png',
    category: 'Fintech',
    tagline: 'Pagos y transferencias rápidas y seguras',
    primaryColor: '#0D3330',
    agentsAvailable: 7,
    config: {
      botName: 'Asistente Félix',
      botSubtitle: 'Soporte de pagos',
      primaryColor: '#0D3330',
      clientLogo: '/logos/sicredi-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Félix. ¿Cómo puedo ayudarte?',
      quickReplies: [
        { label: 'Consultar mis pagos', value: 'payments' },
        { label: 'Problema con una transferencia', value: 'transfer_issue' },
        { label: 'Activar mi cuenta', value: 'activate' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'fx-1', title: '¿Cómo activar mi cuenta Félix?', mins: 3 },
        { id: 'fx-2', title: '¿Cómo enviar dinero a otro usuario?', mins: 2 },
        { id: 'fx-3', title: '¿Cuánto demora una transferencia?', mins: 2 },
        { id: 'fx-4', title: 'Límites de transferencia y retiro', mins: 3 },
        { id: 'fx-5', title: '¿Qué hacer si mi transferencia falló?', mins: 3 },
        { id: 'fx-6', title: 'Seguridad y protección de mis datos', mins: 4 },
        { id: 'fx-7', title: '¿Cómo vincular mi cuenta bancaria?', mins: 3 },
      ],
    },
  },
  {
    id: 'mercadolibre',
    name: 'Mercado Libre',
    logo: '/logos/mercadolibre-logo.png',
    category: 'Ecommerce',
    tagline: 'Compras, ventas y resolución de disputas',
    primaryColor: '#F59E0B',
    agentsAvailable: 20,
    config: {
      botName: 'Asistente Mercado Libre',
      botSubtitle: 'Soporte de compras',
      primaryColor: '#F59E0B',
      clientLogo: '/logos/mercadolibre-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Mercado Libre. ¿Con qué puedo ayudarte?',
      quickReplies: [
        { label: 'Rastrear mi compra', value: 'track' },
        { label: 'Devolver un producto', value: 'return' },
        { label: 'Problema con un pago', value: 'payment_issue' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'ml-1', title: '¿Cómo rastrear el estado de mi compra?', mins: 2 },
        { id: 'ml-2', title: '¿Cómo iniciar una devolución?', mins: 3 },
        { id: 'ml-3', title: '¿Cuándo recibo mi reembolso?', mins: 3 },
        { id: 'ml-4', title: 'Cómo abrir una disputa con el vendedor', mins: 4 },
        { id: 'ml-5', title: 'Política de compra protegida', mins: 3 },
        { id: 'ml-6', title: '¿Cómo calificar al vendedor?', mins: 2 },
        { id: 'ml-7', title: 'Medios de pago aceptados', mins: 2 },
      ],
    },
  },
  {
    id: 'naranjax',
    name: 'Naranja X',
    logo: '/logos/nx-logo.png',
    category: 'Fintech',
    tagline: 'Tu billetera digital y tarjeta de crédito',
    primaryColor: '#F97316',
    agentsAvailable: 11,
    config: {
      botName: 'Asistente Naranja X',
      botSubtitle: 'Finanzas personales',
      primaryColor: '#F97316',
      clientLogo: '/logos/nx-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Naranja X. ¿En qué te ayudo?',
      quickReplies: [
        { label: 'Ver mis movimientos', value: 'movements' },
        { label: 'Problema con mi tarjeta', value: 'card_issue' },
        { label: 'Pedir adelanto de sueldo', value: 'advance' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'nx-1', title: '¿Cómo ver mis movimientos y resumen?', mins: 2 },
        { id: 'nx-2', title: '¿Cuál es el límite de mi tarjeta?', mins: 2 },
        { id: 'nx-3', title: 'Cómo pedir adelanto de sueldo', mins: 3 },
        { id: 'nx-4', title: '¿Cómo bloquear o reportar mi tarjeta?', mins: 2 },
        { id: 'nx-5', title: 'Fechas de cierre y vencimiento', mins: 2 },
        { id: 'nx-6', title: '¿Cómo pagar con QR?', mins: 2 },
        { id: 'nx-7', title: 'Beneficios y descuentos de Naranja X', mins: 3 },
      ],
    },
  },
  {
    id: 'carrefour',
    name: 'Carrefour',
    logo: '/logos/carrefour-logo.png',
    category: 'Retail',
    tagline: 'Consultas sobre compras, tarjeta y beneficios',
    primaryColor: '#0052A5',
    agentsAvailable: 9,
    config: {
      botName: 'Asistente Carrefour',
      botSubtitle: 'Atención al cliente',
      primaryColor: '#0052A5',
      clientLogo: '/logos/carrefour-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Carrefour. ¿En qué te puedo ayudar?',
      quickReplies: [
        { label: 'Estado de mi pedido', value: 'order' },
        { label: 'Tarjeta Carrefour', value: 'card' },
        { label: 'Devolución de producto', value: 'return' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'cf-1', title: '¿Cómo ver el estado de mi pedido?', mins: 2 },
        { id: 'cf-2', title: 'Política de devoluciones y cambios', mins: 3 },
        { id: 'cf-3', title: '¿Cómo usar la tarjeta Carrefour?', mins: 3 },
        { id: 'cf-4', title: '¿Cómo canjear puntos y beneficios?', mins: 3 },
        { id: 'cf-5', title: 'Promociones y ofertas del mes', mins: 2 },
        { id: 'cf-6', title: 'Horarios y ubicación de tiendas', mins: 2 },
        { id: 'cf-7', title: 'Compra online: cómo funciona', mins: 3 },
      ],
    },
  },
  {
    id: 'despegar',
    name: 'Despegar',
    logo: '/logos/despegar-logo.png',
    category: 'Viajes',
    tagline: 'Reservas de vuelos, hoteles y paquetes',
    primaryColor: '#5B21B6',
    agentsAvailable: 6,
    config: {
      botName: 'Asistente Despegar',
      botSubtitle: 'Soporte de viajes',
      primaryColor: '#5B21B6',
      clientLogo: '/logos/despegar-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Despegar. ¿Con qué viaje puedo ayudarte?',
      quickReplies: [
        { label: 'Consultar mi reserva', value: 'booking' },
        { label: 'Cambiar un vuelo', value: 'change_flight' },
        { label: 'Solicitar reembolso', value: 'refund' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'dp-1', title: '¿Cómo ver o modificar mi reserva?', mins: 2 },
        { id: 'dp-2', title: '¿Cómo cancelar un vuelo y pedir reembolso?', mins: 4 },
        { id: 'dp-3', title: '¿Cuándo llega mi reembolso?', mins: 3 },
        { id: 'dp-4', title: '¿Cómo hacer el check-in online?', mins: 2 },
        { id: 'dp-5', title: 'Política de equipaje por aerolínea', mins: 4 },
        { id: 'dp-6', title: '¿Cómo cambiar la fecha de un vuelo?', mins: 3 },
        { id: 'dp-7', title: 'Seguro de viaje: coberturas incluidas', mins: 4 },
      ],
    },
  },
  {
    id: 'jetsmart',
    name: 'JetSmart',
    logo: '/logos/sicredi-logo-2.png',
    category: 'Viajes',
    tagline: 'Vuelos low cost con la mejor experiencia',
    primaryColor: '#C41230',
    agentsAvailable: 4,
    config: {
      botName: 'Asistente JetSmart',
      botSubtitle: 'Soporte de vuelos',
      primaryColor: '#C41230',
      clientLogo: '/logos/sicredi-logo-2.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de JetSmart. ¿En qué te ayudo con tu vuelo?',
      quickReplies: [
        { label: 'Estado de mi vuelo', value: 'flight_status' },
        { label: 'Agregar equipaje', value: 'baggage' },
        { label: 'Cambiar fecha de vuelo', value: 'change_date' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'js-1', title: '¿Cómo hacer el check-in online?', mins: 2 },
        { id: 'js-2', title: '¿Cuánto equipaje puedo llevar?', mins: 3 },
        { id: 'js-3', title: '¿Cómo cambiar la fecha de mi vuelo?', mins: 3 },
        { id: 'js-4', title: 'Documentos necesarios para viajar', mins: 2 },
        { id: 'js-5', title: '¿Cómo agregar equipaje adicional?', mins: 2 },
        { id: 'js-6', title: 'Política de cancelación y reembolso', mins: 4 },
        { id: 'js-7', title: '¿Cómo consultar el estado de mi vuelo?', mins: 2 },
      ],
    },
  },
  {
    id: 'eldorado',
    name: 'El Dorado',
    logo: '/logos/eldorado-logo.png',
    category: 'Viajes',
    tagline: 'Experiencias de viaje premium en Latinoamérica',
    primaryColor: '#D97706',
    agentsAvailable: 3,
    config: {
      botName: 'Asistente El Dorado',
      botSubtitle: 'Viajes premium',
      primaryColor: '#D97706',
      clientLogo: '/logos/eldorado-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Bienvenido a El Dorado. ¿Cómo puedo ayudarte con tu viaje?',
      quickReplies: [
        { label: 'Ver mi reserva', value: 'booking' },
        { label: 'Servicios a bordo', value: 'services' },
        { label: 'Check-in online', value: 'checkin' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'ed-1', title: '¿Cómo consultar mi reserva premium?', mins: 2 },
        { id: 'ed-2', title: '¿Qué servicios incluye mi vuelo?', mins: 3 },
        { id: 'ed-3', title: 'Check-in online: paso a paso', mins: 2 },
        { id: 'ed-4', title: 'Política de equipaje premium', mins: 3 },
        { id: 'ed-5', title: '¿Cómo solicitar asistencia especial?', mins: 3 },
        { id: 'ed-6', title: 'Salones VIP y beneficios en aeropuerto', mins: 3 },
        { id: 'ed-7', title: '¿Cómo cancelar o modificar mi reserva?', mins: 4 },
      ],
    },
  },
  {
    id: 'sodimac',
    name: 'Sodimac',
    logo: '/logos/sodimac-logo.png',
    category: 'Retail',
    tagline: 'Todo para el hogar, construcción y decoración',
    primaryColor: '#DC2626',
    agentsAvailable: 8,
    config: {
      botName: 'Asistente Sodimac',
      botSubtitle: 'Atención al cliente',
      primaryColor: '#DC2626',
      clientLogo: '/logos/sodimac-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Sodimac. ¿En qué te puedo ayudar?',
      quickReplies: [
        { label: 'Estado de mi pedido', value: 'order' },
        { label: 'Devolución de producto', value: 'return' },
        { label: 'Garantía', value: 'warranty' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'sd-1', title: '¿Cómo rastrear mi pedido online?', mins: 2 },
        { id: 'sd-2', title: 'Política de cambios y devoluciones', mins: 3 },
        { id: 'sd-3', title: '¿Cómo hacer válida la garantía?', mins: 4 },
        { id: 'sd-4', title: '¿Cómo usar la tarjeta CMR?', mins: 3 },
        { id: 'sd-5', title: 'Horarios de tiendas y sucursales', mins: 2 },
        { id: 'sd-6', title: 'Despacho a domicilio: plazos y costos', mins: 3 },
        { id: 'sd-7', title: 'Retiro en tienda: cómo funciona', mins: 2 },
      ],
    },
  },
  {
    id: 'toyota',
    name: 'Toyota',
    logo: '/logos/toyota-logo.png',
    category: 'Automotriz',
    tagline: 'Servicio técnico, repuestos y posventa',
    primaryColor: '#DC2626',
    agentsAvailable: 5,
    config: {
      botName: 'Asistente Toyota',
      botSubtitle: 'Posventa y soporte',
      primaryColor: '#DC2626',
      clientLogo: '/logos/toyota-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Toyota. ¿En qué puedo ayudarte?',
      quickReplies: [
        { label: 'Turno de service', value: 'service' },
        { label: 'Estado de mi vehículo', value: 'vehicle' },
        { label: 'Repuestos y accesorios', value: 'parts' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'ty-1', title: '¿Cómo agendar un turno de service?', mins: 2 },
        { id: 'ty-2', title: '¿Qué incluye el service de mi Toyota?', mins: 4 },
        { id: 'ty-3', title: 'Garantía oficial Toyota: cobertura y plazos', mins: 5 },
        { id: 'ty-4', title: '¿Cómo identificar repuestos originales?', mins: 3 },
        { id: 'ty-5', title: '¿Dónde encuentro el número VIN de mi auto?', mins: 2 },
        { id: 'ty-6', title: 'Toyota Hybrid: mantenimiento y dudas', mins: 5 },
        { id: 'ty-7', title: '¿Cómo encontrar un concesionario oficial?', mins: 2 },
      ],
    },
  },
  {
    id: 'volkswagen',
    name: 'Volkswagen',
    logo: '/logos/vw-logo.png',
    category: 'Automotriz',
    tagline: 'Atención posventa y concesionarios oficiales',
    primaryColor: '#1E3A8A',
    agentsAvailable: 6,
    config: {
      botName: 'Asistente Volkswagen',
      botSubtitle: 'Posventa VW',
      primaryColor: '#1E3A8A',
      clientLogo: '/logos/vw-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Volkswagen. ¿En qué puedo ayudarte hoy?',
      quickReplies: [
        { label: 'Agendar service', value: 'service' },
        { label: 'Garantía', value: 'warranty' },
        { label: 'Encontrar concesionario', value: 'dealer' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'vw-1', title: '¿Cómo agendar service en un concesionario?', mins: 2 },
        { id: 'vw-2', title: 'Garantía oficial Volkswagen: términos', mins: 5 },
        { id: 'vw-3', title: '¿Cómo encontrar un concesionario oficial?', mins: 2 },
        { id: 'vw-4', title: 'Actualización de software y sistemas', mins: 4 },
        { id: 'vw-5', title: 'Repuestos originales VW: dónde comprarlos', mins: 3 },
        { id: 'vw-6', title: '¿Cómo registrar mi vehículo en My VW?', mins: 3 },
        { id: 'vw-7', title: 'Modelos eléctricos e híbridos VW', mins: 4 },
      ],
    },
  },
  {
    id: 'nestle',
    name: 'Nestlé',
    logo: '/logos/nestle-logo.png',
    category: 'Consumo',
    tagline: 'Consultas sobre productos y promociones',
    primaryColor: '#005BAC',
    agentsAvailable: 4,
    config: {
      botName: 'Asistente Nestlé',
      botSubtitle: 'Atención al consumidor',
      primaryColor: '#005BAC',
      clientLogo: '/logos/nestle-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Nestlé. ¿En qué puedo ayudarte?',
      quickReplies: [
        { label: 'Información de producto', value: 'product' },
        { label: 'Promociones y descuentos', value: 'promo' },
        { label: 'Reclamo de calidad', value: 'quality' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'ns-1', title: 'Información nutricional de mis productos', mins: 2 },
        { id: 'ns-2', title: '¿Dónde comprar productos Nestlé?', mins: 2 },
        { id: 'ns-3', title: '¿Cómo hacer un reclamo de calidad?', mins: 3 },
        { id: 'ns-4', title: 'Fecha de vencimiento y conservación', mins: 2 },
        { id: 'ns-5', title: 'Alérgenos e ingredientes destacados', mins: 3 },
        { id: 'ns-6', title: 'Programa Club Nestlé: beneficios', mins: 3 },
        { id: 'ns-7', title: 'Productos sin gluten y opciones especiales', mins: 3 },
      ],
    },
  },
  {
    id: 'nespresso',
    name: 'Nespresso',
    logo: '/logos/nespresso-logo.png',
    category: 'Consumo',
    tagline: 'Cápsulas, máquinas y club Nespresso',
    primaryColor: '#1C1C1C',
    agentsAvailable: 5,
    config: {
      botName: 'Asistente Nespresso',
      botSubtitle: 'Club Nespresso',
      primaryColor: '#1C1C1C',
      clientLogo: '/logos/nespresso-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Bienvenido a Nespresso. ¿En qué puedo ayudarte?',
      quickReplies: [
        { label: 'Pedir cápsulas', value: 'capsules' },
        { label: 'Soporte para mi máquina', value: 'machine' },
        { label: 'Mi cuenta Club', value: 'club' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'np-1', title: '¿Cómo pedir cápsulas online?', mins: 2 },
        { id: 'np-2', title: 'Mi máquina no funciona: soluciones', mins: 4 },
        { id: 'np-3', title: '¿Cómo unirme al Club Nespresso?', mins: 3 },
        { id: 'np-4', title: 'Programa de reciclado de cápsulas', mins: 3 },
        { id: 'np-5', title: 'Garantía de la máquina: cobertura', mins: 4 },
        { id: 'np-6', title: '¿Cómo descalcificar mi máquina?', mins: 3 },
        { id: 'np-7', title: 'Sabores y líneas de cápsulas disponibles', mins: 2 },
      ],
    },
  },
  {
    id: 'mondelez',
    name: 'Mondelēz',
    logo: '/logos/mondelez-logo.png',
    category: 'Consumo',
    tagline: 'Marcas líderes en snacks y chocolates',
    primaryColor: '#5B21B6',
    agentsAvailable: 3,
    config: {
      botName: 'Asistente Mondelēz',
      botSubtitle: 'Atención al consumidor',
      primaryColor: '#5B21B6',
      clientLogo: '/logos/mondelez-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Mondelēz. ¿En qué puedo ayudarte?',
      quickReplies: [
        { label: 'Información de producto', value: 'product' },
        { label: 'Reclamo de calidad', value: 'quality' },
        { label: 'Promociones', value: 'promo' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'mz-1', title: 'Ingredientes y alérgenos por producto', mins: 3 },
        { id: 'mz-2', title: '¿Dónde comprar mis productos favoritos?', mins: 2 },
        { id: 'mz-3', title: '¿Cómo reportar un problema de calidad?', mins: 3 },
        { id: 'mz-4', title: 'Promociones y concursos vigentes', mins: 2 },
        { id: 'mz-5', title: 'Opciones sin gluten en Mondelēz', mins: 3 },
        { id: 'mz-6', title: 'Información nutricional detallada', mins: 3 },
        { id: 'mz-7', title: 'Compromiso de sustentabilidad', mins: 4 },
      ],
    },
  },
  {
    id: 'pg',
    name: 'P&G',
    logo: '/logos/pg-logo.png',
    category: 'Consumo',
    tagline: 'Hogar, belleza y cuidado personal',
    primaryColor: '#003087',
    agentsAvailable: 4,
    config: {
      botName: 'Asistente P&G',
      botSubtitle: 'Atención al consumidor',
      primaryColor: '#003087',
      clientLogo: '/logos/pg-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de P&G. ¿Cómo puedo ayudarte?',
      quickReplies: [
        { label: 'Información de producto', value: 'product' },
        { label: 'Dónde comprar', value: 'where_to_buy' },
        { label: 'Reclamo', value: 'claim' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'pg-1', title: 'Información sobre ingredientes por marca', mins: 3 },
        { id: 'pg-2', title: '¿Dónde comprar productos P&G?', mins: 2 },
        { id: 'pg-3', title: '¿Cómo hacer un reclamo de producto?', mins: 3 },
        { id: 'pg-4', title: 'Seguridad y uso correcto de los productos', mins: 4 },
        { id: 'pg-5', title: 'Productos P&G para el hogar', mins: 2 },
        { id: 'pg-6', title: 'Cuidado personal: productos disponibles', mins: 2 },
        { id: 'pg-7', title: 'Compromiso ambiental de P&G', mins: 4 },
      ],
    },
  },
  {
    id: 'seara',
    name: 'Seara',
    logo: '/logos/seara-logo.png',
    category: 'Consumo',
    tagline: 'Alimentos frescos y procesados de calidad',
    primaryColor: '#DC2626',
    agentsAvailable: 4,
    config: {
      botName: 'Asistente Seara',
      botSubtitle: 'Atención al consumidor',
      primaryColor: '#DC2626',
      clientLogo: '/logos/seara-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Seara. ¿En qué puedo ayudarte?',
      quickReplies: [
        { label: 'Información nutricional', value: 'nutrition' },
        { label: 'Dónde comprar', value: 'where_to_buy' },
        { label: 'Reclamo de calidad', value: 'quality' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'sr-1', title: 'Información nutricional de mis productos', mins: 2 },
        { id: 'sr-2', title: '¿Dónde comprar productos Seara?', mins: 2 },
        { id: 'sr-3', title: '¿Cómo reportar un problema de calidad?', mins: 3 },
        { id: 'sr-4', title: 'Conservación y almacenamiento correcto', mins: 3 },
        { id: 'sr-5', title: 'Recetas con productos Seara', mins: 2 },
        { id: 'sr-6', title: 'Alérgenos e ingredientes destacados', mins: 3 },
        { id: 'sr-7', title: 'Línea de productos sin conservantes', mins: 3 },
      ],
    },
  },
  {
    id: 'sicoob',
    name: 'SICOOB',
    logo: '/logos/netflix-logo-1.png',
    category: 'Banca',
    tagline: 'Sistema de cooperativas de crédito del Brasil',
    primaryColor: '#007A3D',
    agentsAvailable: 10,
    config: {
      botName: 'Asistente SICOOB',
      botSubtitle: 'Cooperativa de crédito',
      primaryColor: '#007A3D',
      clientLogo: '/logos/netflix-logo-1.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de SICOOB. ¿En qué puedo ayudarte hoy?',
      quickReplies: [
        { label: 'Consultar mi cuenta', value: 'account' },
        { label: 'Solicitar crédito', value: 'credit' },
        { label: 'Tarjeta de débito/crédito', value: 'card' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'sb-1', title: '¿Cómo abrir mi cuenta cooperativa?', mins: 4 },
        { id: 'sb-2', title: '¿Cómo acceder al internet banking?', mins: 2 },
        { id: 'sb-3', title: '¿Cómo solicitar un crédito?', mins: 5 },
        { id: 'sb-4', title: 'Tasas y rendimiento de inversiones', mins: 4 },
        { id: 'sb-5', title: '¿Qué es el sistema SICOOB?', mins: 3 },
        { id: 'sb-6', title: 'Seguro de vida y beneficios cooperativos', mins: 4 },
        { id: 'sb-7', title: 'Transferencias y PIX desde mi cuenta', mins: 2 },
      ],
    },
  },
  {
    id: 'supergasbras',
    name: 'Supergasbras',
    logo: '/logos/netflix-logo.png',
    category: 'Energía',
    tagline: 'Distribución de gas y servicios energéticos',
    primaryColor: '#E35A1A',
    agentsAvailable: 6,
    config: {
      botName: 'Asistente Supergasbras',
      botSubtitle: 'Soporte energético',
      primaryColor: '#E35A1A',
      clientLogo: '/logos/netflix-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Supergasbras. ¿En qué puedo ayudarte?',
      quickReplies: [
        { label: 'Solicitar recarga de gas', value: 'refill' },
        { label: 'Estado de mi pedido', value: 'order' },
        { label: 'Emergencia', value: 'emergency' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'sg-1', title: '¿Cómo solicitar una recarga de gas?', mins: 2 },
        { id: 'sg-2', title: '¿Cuánto demora la entrega?', mins: 2 },
        { id: 'sg-3', title: '¿Qué hacer en caso de fuga de gas?', mins: 3 },
        { id: 'sg-4', title: '¿Cómo pagar mi pedido?', mins: 2 },
        { id: 'sg-5', title: 'Instalación segura de cilindros', mins: 4 },
        { id: 'sg-6', title: 'Zonas de cobertura y distribución', mins: 2 },
        { id: 'sg-7', title: 'Recomendaciones de seguridad en el hogar', mins: 4 },
      ],
    },
  },
  {
    id: 'buenosaires',
    name: 'Buenos Aires Ciudad',
    logo: '/logos/ba-logo.png',
    category: 'Gobierno',
    tagline: 'Trámites y servicios del Gobierno de la Ciudad',
    primaryColor: '#F5C800',
    agentsAvailable: 15,
    config: {
      botName: 'Asistente BA Ciudad',
      botSubtitle: 'Atención ciudadana',
      primaryColor: '#F5C800',
      clientLogo: '/logos/ba-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de Buenos Aires Ciudad. ¿Con qué trámite puedo ayudarte?',
      quickReplies: [
        { label: 'Turnos y trámites', value: 'appointments' },
        { label: 'Infracciones de tránsito', value: 'traffic' },
        { label: 'Servicios educativos', value: 'education' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'ba-1', title: '¿Cómo sacar un turno online en BA?', mins: 2 },
        { id: 'ba-2', title: '¿Cómo pagar una infracción de tránsito?', mins: 3 },
        { id: 'ba-3', title: 'Trámites del DNI en la Ciudad', mins: 4 },
        { id: 'ba-4', title: 'Servicios de salud: hospitales y CeSAC', mins: 3 },
        { id: 'ba-5', title: 'Inscripción escolar en la Ciudad', mins: 4 },
        { id: 'ba-6', title: '¿Cómo denunciar un problema urbano?', mins: 2 },
        { id: 'ba-7', title: 'Habilitaciones comerciales y permisos', mins: 5 },
      ],
    },
  },
  {
    id: 'provba',
    name: 'Prov. Buenos Aires',
    logo: '/logos/provBA-logo.png',
    category: 'Gobierno',
    tagline: 'Servicios del Gobierno de la Provincia de Buenos Aires',
    primaryColor: '#00B4D8',
    agentsAvailable: 12,
    config: {
      botName: 'Asistente Prov. BA',
      botSubtitle: 'Atención ciudadana',
      primaryColor: '#00B4D8',
      clientLogo: '/logos/provBA-logo.png',
      welcomeMessage: '¡Hola, {{nombre}}! Soy el asistente de la Provincia de Buenos Aires. ¿Cómo puedo ayudarte?',
      quickReplies: [
        { label: 'Consultar un trámite', value: 'tramite' },
        { label: 'ARBA - Impuestos', value: 'taxes' },
        { label: 'Salud y hospitales', value: 'health' },
        { label: 'Hablar con un agente', value: 'human_handoff' },
      ],
      faqArticles: [
        { id: 'pb-1', title: '¿Cómo consultar mis impuestos en ARBA?', mins: 3 },
        { id: 'pb-2', title: '¿Cómo sacar turno en un hospital público?', mins: 3 },
        { id: 'pb-3', title: 'Trámites online disponibles en la Provincia', mins: 4 },
        { id: 'pb-4', title: '¿Cómo renovar la licencia de conducir?', mins: 4 },
        { id: 'pb-5', title: 'Servicios educativos provinciales', mins: 3 },
        { id: 'pb-6', title: '¿Cómo tramitar un subsidio o beneficio?', mins: 5 },
        { id: 'pb-7', title: 'Registro del Automotor: trámites', mins: 4 },
      ],
    },
  },
]

export const CATEGORIES = [
  'Todos', 'Telecom', 'Fintech', 'Banca', 'Ecommerce',
  'Retail', 'Viajes', 'Automotriz', 'Consumo', 'Gobierno', 'Energía',
]
