export const HELP_COLLECTIONS = [
  {
    id: 'getting-started',
    title: 'Primeros pasos',
    description: 'Cómo configurar tu cuenta y crear tu primer bot',
    articles: 8,
    items: [
      { id: 'gs-1', title: '¿Qué es Botmaker?', mins: 2 },
      { id: 'gs-2', title: 'Cómo crear tu primer bot', mins: 5 },
      { id: 'gs-3', title: 'Conectar un canal de WhatsApp', mins: 4 },
      { id: 'gs-4', title: 'Agregar agentes humanos a tu cuenta', mins: 3 },
      { id: 'gs-5', title: 'Entender el panel de control', mins: 3 },
      { id: 'gs-6', title: 'Configurar el horario de atención', mins: 2 },
      { id: 'gs-7', title: 'Invitar a tu equipo', mins: 2 },
      { id: 'gs-8', title: 'Primeros pasos con el Webchat', mins: 4 },
    ],
  },
  {
    id: 'ai-agents',
    title: 'Agentes de IA',
    description: 'Creá y configurá agentes inteligentes para tu negocio',
    articles: 12,
    items: [
      { id: 'ai-1', title: '¿Qué es un Agente de IA en Botmaker?', mins: 3 },
      { id: 'ai-2', title: 'Cómo entrenar a tu agente con documentos', mins: 6 },
      { id: 'ai-3', title: 'Configurar el tono y personalidad del bot', mins: 4 },
      { id: 'ai-4', title: 'Manejo de preguntas fuera del alcance', mins: 3 },
      { id: 'ai-5', title: 'Integrar el agente con tu base de conocimiento', mins: 5 },
      { id: 'ai-6', title: 'Métricas de performance del agente', mins: 4 },
      { id: 'ai-7', title: 'Escalada automática a agente humano', mins: 3 },
      { id: 'ai-8', title: 'Prueba y ajuste de respuestas', mins: 5 },
      { id: 'ai-9', title: 'Variables y personalización de respuestas', mins: 4 },
      { id: 'ai-10', title: 'Flujos condicionales con IA', mins: 6 },
      { id: 'ai-11', title: 'Limitaciones y buenas prácticas', mins: 3 },
      { id: 'ai-12', title: 'Modelos de IA disponibles', mins: 2 },
    ],
  },
  {
    id: 'channels',
    title: 'Canales',
    description: 'WhatsApp, Instagram, Webchat y más',
    articles: 15,
    items: [
      { id: 'ch-1', title: 'Conectar WhatsApp Business API', mins: 7 },
      { id: 'ch-2', title: 'Configurar Instagram Direct', mins: 5 },
      { id: 'ch-3', title: 'Integrar el Webchat en tu sitio web', mins: 4 },
      { id: 'ch-4', title: 'Conectar Facebook Messenger', mins: 5 },
      { id: 'ch-5', title: 'Configurar Telegram', mins: 3 },
      { id: 'ch-6', title: 'WhatsApp Personal — Canales Compartidos', mins: 6 },
      { id: 'ch-7', title: 'Múltiples números de WhatsApp', mins: 4 },
      { id: 'ch-8', title: 'Personalizar el widget de Webchat', mins: 5 },
      { id: 'ch-9', title: 'Plantillas de mensajes en WhatsApp', mins: 6 },
      { id: 'ch-10', title: 'Notificaciones push y proactivas', mins: 4 },
      { id: 'ch-11', title: 'Gestión de canales desde el inbox', mins: 3 },
      { id: 'ch-12', title: 'Horarios por canal', mins: 2 },
      { id: 'ch-13', title: 'Transferencia entre canales', mins: 3 },
      { id: 'ch-14', title: 'Límites y restricciones por canal', mins: 3 },
      { id: 'ch-15', title: 'Verificación de número de WhatsApp', mins: 8 },
    ],
  },
  {
    id: 'flows',
    title: 'Flujos y automatizaciones',
    description: 'Diseñá conversaciones y automatizá procesos',
    articles: 10,
    items: [
      { id: 'fl-1', title: 'Crear un flujo de conversación', mins: 5 },
      { id: 'fl-2', title: 'Nodos y conectores disponibles', mins: 4 },
      { id: 'fl-3', title: 'Condiciones y ramificaciones', mins: 5 },
      { id: 'fl-4', title: 'Variables en los flujos', mins: 4 },
      { id: 'fl-5', title: 'Integraciones con APIs externas', mins: 6 },
      { id: 'fl-6', title: 'Acciones de CRM en flujos', mins: 5 },
      { id: 'fl-7', title: 'Flujos de captación de leads', mins: 4 },
      { id: 'fl-8', title: 'Automatizar respuestas fuera de horario', mins: 3 },
      { id: 'fl-9', title: 'Testear un flujo antes de publicar', mins: 3 },
      { id: 'fl-10', title: 'Versionado y rollback de flujos', mins: 3 },
    ],
  },
  {
    id: 'inbox',
    title: 'Inbox y agentes',
    description: 'Gestión de conversaciones y equipos',
    articles: 9,
    items: [
      { id: 'in-1', title: 'Cómo funciona el Inbox unificado', mins: 3 },
      { id: 'in-2', title: 'Asignar conversaciones a agentes', mins: 3 },
      { id: 'in-3', title: 'Notas internas en conversaciones', mins: 2 },
      { id: 'in-4', title: 'Respuestas guardadas (snippets)', mins: 3 },
      { id: 'in-5', title: 'Etiquetas y categorías', mins: 2 },
      { id: 'in-6', title: 'Métricas de tiempo de respuesta', mins: 4 },
      { id: 'in-7', title: 'Roles y permisos del equipo', mins: 3 },
      { id: 'in-8', title: 'Notificaciones para agentes', mins: 2 },
      { id: 'in-9', title: 'Cola de espera y distribución automática', mins: 4 },
    ],
  },
  {
    id: 'integrations',
    title: 'Integraciones',
    description: 'Conectá Botmaker con tus herramientas',
    articles: 7,
    items: [
      { id: 'int-1', title: 'Integración con HubSpot', mins: 5 },
      { id: 'int-2', title: 'Integración con Salesforce', mins: 6 },
      { id: 'int-3', title: 'Webhooks — enviar y recibir datos', mins: 5 },
      { id: 'int-4', title: 'Zapier y Make (Integromat)', mins: 4 },
      { id: 'int-5', title: 'API REST de Botmaker', mins: 7 },
      { id: 'int-6', title: 'Integración con Google Sheets', mins: 4 },
      { id: 'int-7', title: 'Single Sign-On (SSO)', mins: 5 },
    ],
  },
]
